version: 2

sources:
  - name: xch
    schema: dev
    tables:
      - name: emp

models:
  - name: emp
    description: Employee details fetched from source table `xch.emp`
    columns:
      - name: emp_no
        description: Unique ID for each employee
      - name: dno
        description: Department number (foreign key from dept)
      - name: name
        description: Name of the employee
      - name: sal
        description: sal
      - name: dob
        description: dob
      - name: remark
        description: remark

seeds:
  - name: dept
    description: Department mapping for employees
    columns:
      - name: dno
        description: Unique department number
      - name: dname
        description: Name of the department
